name: all_platforms_classification
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image: ^4.5.2
  tuple: ^2.0.2
  loading_indicator: ^3.1.1
  universal_io: ^2.2.2
  universal_platform: ^1.1.0
  lite_rt_for_flutter:
    path: ../../../lite_rt_for_flutter
  lite_rt_for_flutter_libs:
    path: ../../../lite_rt_for_flutter_libs/base/lite_rt_for_flutter_libs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

