name: lite_rt_for_flutter
description: Plugin to run tf lite models in flutter apps.
version: 0.0.1
homepage: https://github.com/CaptainDario/lite_rt_for_flutter
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  lite_rt_for_dart:
    path: ../lite_rt_for_dart
  lite_rt_for_flutter_libs:
    path: ../lite_rt_for_flutter_libs/lite_rt_for_flutter_libs

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

