name: select_ops_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  lite_rt_for_flutter:
    path: ../../../lite_rt_for_flutter
  
  # base libs
  lite_rt_for_flutter_libs_android:
    git:
      url: https://github.com/CaptainDario/lite_rt_for_flutter_libs
      path: base/lite_rt_for_flutter_libs_android
  lite_rt_for_flutter_libs_ios:
    path: /Users/darioklepoch/dev/flutter_packages/lite_rt_for_flutter_libs/base/lite_rt_for_flutter_libs_ios

  # flex libs
  lite_rt_for_flutter_libs_flex_delegate_ios:
    git:
      url: https://github.com/CaptainDario/lite_rt_for_flutter_libs
      path: flex/lite_rt_for_flutter_libs_flex_delegate_ios
  lite_rt_for_flutter_libs_flex_delegate_android:
    git:
      url: https://github.com/CaptainDario/lite_rt_for_flutter_libs
      path: flex/lite_rt_for_flutter_libs_flex_delegate_android

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - select_ops_model/converted_model.tflite
    - select_ops_model/mobilenet_quant.tflite
